import type { Order, User, DeliveryHistory } from '../types';

export const mockOrders: Order[] = [
  {
    id: '1',
    emetteurId: 'client1',
    emetteurName: 'Jean Dupont',
    recepteurId: 'client2',
    recepteurName: 'Marie Martin',
    recepteurAddress: '15 Rue de la Paix, Paris',
    livreurId: 'livreur1',
    livreurName: 'Ahmed Hassan',
    status: 'in_transit',
    description: 'Package with electronic items',
    weight: 2.5,
    pickupAddress: '25 Avenue des Champs, Paris',
    deliveryAddress: '15 Rue de la Paix, Paris',
    latitude: 48.8566,
    longitude: 2.3522,
    createdAt: new Date('2025-11-24T08:00:00'),
    updatedAt: new Date('2025-11-24T10:30:00'),
  },
  {
    id: '2',
    emetteurId: 'client3',
    emetteurName: 'Sophie Bernard',
    recepteurId: 'client1',
    recepteurName: 'Jean Dupont',
    recepteurAddress: '25 Avenue des Champs, Paris',
    status: 'confirmed',
    description: 'Documents and books',
    weight: 1.2,
    pickupAddress: '10 Boulevard Saint-Michel, Paris',
    deliveryAddress: '25 Avenue des Champs, Paris',
    latitude: 48.8606,
    longitude: 2.3376,
    createdAt: new Date('2025-11-24T09:15:00'),
    updatedAt: new Date('2025-11-24T09:15:00'),
  },
  {
    id: '3',
    emetteurId: 'client1',
    emetteurName: 'Jean Dupont',
    recepteurId: 'client4',
    recepteurName: 'Pierre Dubois',
    recepteurAddress: '8 Rue du Commerce, Lyon',
    status: 'confirmed',
    description: 'Fashion accessories',
    weight: 0.8,
    pickupAddress: '25 Avenue des Champs, Paris',
    deliveryAddress: '8 Rue du Commerce, Lyon',
    latitude: 45.7640,
    longitude: 4.8357,
    createdAt: new Date('2025-11-24T07:30:00'),
    updatedAt: new Date('2025-11-24T08:00:00'),
  },
  {
    id: '4',
    emetteurId: 'client2',
    emetteurName: 'Marie Martin',
    recepteurId: 'client5',
    recepteurName: 'Claire Rousseau',
    recepteurAddress: '33 Cours Mirabeau, Marseille',
    livreurId: 'livreur2',
    livreurName: 'Karim Benzema',
    status: 'picked_up',
    description: 'Gift package',
    weight: 1.5,
    pickupAddress: '15 Rue de la Paix, Paris',
    deliveryAddress: '33 Cours Mirabeau, Marseille',
    latitude: 43.2965,
    longitude: 5.3698,
    createdAt: new Date('2025-11-24T06:00:00'),
    updatedAt: new Date('2025-11-24T11:00:00'),
  },
  {
    id: '5',
    emetteurId: 'client5',
    emetteurName: 'Claire Rousseau',
    recepteurId: 'client3',
    recepteurName: 'Sophie Bernard',
    recepteurAddress: '10 Boulevard Saint-Michel, Paris',
    livreurId: 'livreur1',
    livreurName: 'Ahmed Hassan',
    status: 'delivered',
    description: 'Handmade crafts',
    weight: 3.0,
    pickupAddress: '33 Cours Mirabeau, Marseille',
    deliveryAddress: '10 Boulevard Saint-Michel, Paris',
    latitude: 48.8534,
    longitude: 2.3428,
    createdAt: new Date('2025-11-23T10:00:00'),
    updatedAt: new Date('2025-11-24T09:00:00'),
  },
];

export const mockUsers: User[] = [
  {
    id: 'client1',
    name: 'Jean Dupont',
    email: 'jean.dupont@email.com',
    role: 'client',
    phone: '+33 1 23 45 67 89',
    address: '25 Avenue des Champs, Paris',
    latitude: 48.8566,
    longitude: 2.3522,
  },
  {
    id: 'client2',
    name: 'Marie Martin',
    email: 'marie.martin@email.com',
    role: 'client',
    phone: '+33 1 98 76 54 32',
    address: '15 Rue de la Paix, Paris',
    latitude: 48.8584,
    longitude: 2.3470,
  },
  {
    id: 'client3',
    name: 'Sophie Bernard',
    email: 'sophie.bernard@email.com',
    role: 'client',
    phone: '+33 1 45 67 89 01',
    address: '10 Boulevard Saint-Michel, Paris',
    latitude: 48.8534,
    longitude: 2.3428,
  },
  {
    id: 'client4',
    name: 'Pierre Dubois',
    email: 'pierre.dubois@email.com',
    role: 'client',
    phone: '+33 4 78 90 12 34',
    address: '8 Rue du Commerce, Lyon',
    latitude: 45.7640,
    longitude: 4.8357,
  },
  {
    id: 'client5',
    name: 'Claire Rousseau',
    email: 'claire.rousseau@email.com',
    role: 'client',
    phone: '+33 4 91 23 45 67',
    address: '33 Cours Mirabeau, Marseille',
    latitude: 43.2965,
    longitude: 5.3698,
  },
  {
    id: 'livreur1',
    name: 'Ahmed Hassan',
    email: 'ahmed.hassan@email.com',
    role: 'livreur',
    phone: '+33 6 12 34 56 78',
    latitude: 48.8566,
    longitude: 2.3522,
  },
  {
    id: 'livreur2',
    name: 'Karim Benzema',
    email: 'karim.benzema@email.com',
    role: 'livreur',
    phone: '+33 6 87 65 43 21',
    latitude: 48.8606,
    longitude: 2.3376,
  },
];

export const mockDeliveryHistory: DeliveryHistory[] = [
  {
    id: 'h1',
    orderId: '5',
    livreurId: 'livreur1',
    completedAt: new Date('2025-11-24T09:00:00'),
  },
  {
    id: 'h2',
    orderId: '6',
    livreurId: 'livreur1',
    completedAt: new Date('2025-11-23T16:30:00'),
  },
  {
    id: 'h3',
    orderId: '7',
    livreurId: 'livreur1',
    completedAt: new Date('2025-11-23T12:15:00'),
  },
];